name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Debug with Gradle
        run: ./gradlew :app:assembleDebug
      - name: Upload a Build Artifact
        if: success()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build-artifact
          path: |
            app\build\outputs\apk\debug
